language: ruby
rvm:
    - 2.1.0
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
before_script:
    - bundle exec rake db:migrate
bundler_args: --without development production
script: 'rake db:test:prepare && rake test && bundle exec rake teaspoon'
